import pandas as pd
import numpy as np

import pylibkriging as lk

results = pd.read_parquet('openfast_lin_results_sampling.parquet')
l1fx = np.array(results['l1fx'])
l1fy = np.array(results['l1fy'])
l1fz = np.array(results['l1fz'])
l1px = np.array(results['l1px'])
l1py = np.array(results['l1py'])
l1pz = np.array(results['l1pz'])
l1vx = np.array(results['l1vx'])
l1vy = np.array(results['l1vy'])
l1vz = np.array(results['l1vz'])
l2fx = np.array(results['l2fx'])
l2fy = np.array(results['l2fy'])
l2fz = np.array(results['l2fz'])
l2px = np.array(results['l2px'])
l2py = np.array(results['l2py'])
l2pz = np.array(results['l2pz'])
l2vx = np.array(results['l2vx'])
l2vy = np.array(results['l2vy'])
l2vz = np.array(results['l2vz'])
l3fx = np.array(results['l3fx'])
l3fy = np.array(results['l3fy'])
l3fz = np.array(results['l3fz'])
l3px = np.array(results['l3px'])
l3py = np.array(results['l3py'])
l3pz = np.array(results['l3pz'])
l3vx = np.array(results['l3vx'])
l3vy = np.array(results['l3vy'])
l3vz = np.array(results['l3vz'])
wave_elevs = np.array(results['wave_elev'])
xt1 = np.column_stack((l1fx, l1fy, l1fz, wave_elevs))
xt2 = np.column_stack((l2fx, l2fy, l2fz, wave_elevs))
xt3 = np.column_stack((l3fx, l3fy, l3fz, wave_elevs))

model_l1px = lk.Kriging(l1px, xt1, 'gauss')
model_l1py = lk.Kriging(l1py, xt1, 'gauss')
model_l1pz = lk.Kriging(l1pz, xt1, 'gauss')
model_l1vx = lk.Kriging(l1vx, xt1, 'gauss')
model_l1vy = lk.Kriging(l1vy, xt1, 'gauss')
model_l1vz = lk.Kriging(l1vz, xt1, 'gauss')
model_l2px = lk.Kriging(l2px, xt2, 'gauss')
model_l2py = lk.Kriging(l2py, xt2, 'gauss')
model_l2pz = lk.Kriging(l2pz, xt2, 'gauss')
model_l2vx = lk.Kriging(l2vx, xt2, 'gauss')
model_l2vy = lk.Kriging(l2vy, xt2, 'gauss')
model_l2vz = lk.Kriging(l2vz, xt2, 'gauss')
model_l3px = lk.Kriging(l3px, xt3, 'gauss')
model_l3py = lk.Kriging(l3py, xt3, 'gauss')
model_l3pz = lk.Kriging(l3pz, xt3, 'gauss')
model_l3vx = lk.Kriging(l3vx, xt3, 'gauss')
model_l3vy = lk.Kriging(l3vy, xt3, 'gauss')
model_l3vz = lk.Kriging(l3vz, xt3, 'gauss')

model_l1px.save('models/model_l1px.h5')
model_l1py.save('models/model_l1py.h5')
model_l1pz.save('models/model_l1pz.h5')
model_l1vx.save('models/model_l1vx.h5')
model_l1vy.save('models/model_l1vy.h5')
model_l1vz.save('models/model_l1vz.h5')
model_l2px.save('models/model_l2px.h5')
model_l2py.save('models/model_l2py.h5')
model_l2pz.save('models/model_l2pz.h5')
model_l2vx.save('models/model_l2vx.h5')
model_l2vy.save('models/model_l2vy.h5')
model_l2vz.save('models/model_l2vz.h5')
model_l3px.save('models/model_l3px.h5')
model_l3py.save('models/model_l3py.h5')
model_l3pz.save('models/model_l3pz.h5')
model_l3vx.save('models/model_l3vx.h5')
model_l3vy.save('models/model_l3vy.h5')
model_l3vz.save('models/model_l3vz.h5')

print('Done.')
