import numpy as np

l1px = np.load('npy_files/l1px.npy')
l1py = np.load('npy_files/l1py.npy')
l1pz = np.load('npy_files/l1pz.npy')
l1vx = np.load('npy_files/l1vx.npy')
l1vy = np.load('npy_files/l1vy.npy')
l1vz = np.load('npy_files/l1vz.npy')
l2px = np.load('npy_files/l2px.npy')
l2py = np.load('npy_files/l2py.npy')
l2pz = np.load('npy_files/l2pz.npy')
l2vx = np.load('npy_files/l2vx.npy')
l2vy = np.load('npy_files/l2vy.npy')
l2vz = np.load('npy_files/l2vz.npy')
l3px = np.load('npy_files/l3px.npy')
l3py = np.load('npy_files/l3py.npy')
l3pz = np.load('npy_files/l3pz.npy')
l3vx = np.load('npy_files/l3vx.npy')
l3vy = np.load('npy_files/l3vy.npy')
l3vz = np.load('npy_files/l3vz.npy')
xt1 = np.load('npy_files/xt1.npy')
xt2 = np.load('npy_files/xt2.npy')
xt3 = np.load('npy_files/xt3.npy')

import pylibkriging as lk
model_l1px = lk.Kriging(l1px, xt1, "gauss")
model_l1py = lk.Kriging(l1py, xt1, 'gauss')
model_l1pz = lk.Kriging(l1pz, xt1, 'gauss')
model_l1vx = lk.Kriging(l1vx, xt1, 'gauss')
model_l1vy = lk.Kriging(l1vy, xt1, 'gauss')
model_l1vz = lk.Kriging(l1vz, xt1, 'gauss')
model_l2px = lk.Kriging(l2px, xt2, 'gauss')
model_l2py = lk.Kriging(l2py, xt2, 'gauss')
model_l2pz = lk.Kriging(l2pz, xt2, 'gauss')
model_l2vx = lk.Kriging(l2vx, xt2, 'gauss')
model_l2vy = lk.Kriging(l2vy, xt2, 'gauss')
model_l2vz = lk.Kriging(l2vz, xt2, 'gauss')
model_l3px = lk.Kriging(l3px, xt3, 'gauss')
model_l3py = lk.Kriging(l3py, xt3, 'gauss')
model_l3pz = lk.Kriging(l3pz, xt3, 'gauss')
model_l3vx = lk.Kriging(l3vx, xt3, 'gauss')
model_l3vy = lk.Kriging(l3vy, xt3, 'gauss')
model_l3vz = lk.Kriging(l3vz, xt3, 'gauss')
model_l1px.save('models/model_l1px.h5')
model_l1py.save('models/model_l1py.h5')
model_l1pz.save('models/model_l1pz.h5')
model_l1vx.save('models/model_l1vx.h5')
model_l1vy.save('models/model_l1vy.h5')
model_l1vz.save('models/model_l1vz.h5')
model_l2px.save('models/model_l2px.h5')
model_l2py.save('models/model_l2py.h5')
model_l2pz.save('models/model_l2pz.h5')
model_l2vx.save('models/model_l2vx.h5')
model_l2vy.save('models/model_l2vy.h5')
model_l2vz.save('models/model_l2vz.h5')
model_l3px.save('models/model_l3px.h5')
model_l3py.save('models/model_l3py.h5')
model_l3pz.save('models/model_l3pz.h5')
model_l3vx.save('models/model_l3vx.h5')
model_l3vy.save('models/model_l3vy.h5')
model_l3vz.save('models/model_l3vz.h5')

print('Done.')
